# Generated by Django 4.0.2 on 2022-03-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcabinet', '0004_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
